// ============================================================
// CET-4 & CET-6 核心词汇数据库
// 每条记录: { w:单词, p:音标, pos:词性, m:释义, ex:例句, et:例句翻译 }
// ============================================================

const CET4_WORDS = [
  { w: "abandon", p: "/əˈbændən/", pos: "v.", m: "放弃；抛弃", ex: "He abandoned his career to take care of his family.", et: "他为了照顾家人放弃了事业。" },
  { w: "ability", p: "/əˈbɪləti/", pos: "n.", m: "能力；才能", ex: "She has the ability to solve complex problems.", et: "她有能力解决复杂的问题。" },
  { w: "absorb", p: "/əbˈzɔːrb/", pos: "v.", m: "吸收；吸引", ex: "Plants absorb carbon dioxide from the air.", et: "植物从空气中吸收二氧化碳。" },
  { w: "abstract", p: "/ˈæbstrækt/", pos: "adj.", m: "抽象的", ex: "Beauty is an abstract concept.", et: "美是一个抽象的概念。" },
  { w: "academic", p: "/ˌækəˈdemɪk/", pos: "adj.", m: "学术的；学院的", ex: "The university is known for its academic excellence.", et: "这所大学以其学术卓越而闻名。" },
  { w: "accept", p: "/əkˈsept/", pos: "v.", m: "接受；同意", ex: "Please accept our sincere apologies.", et: "请接受我们真诚的道歉。" },
  { w: "access", p: "/ˈækses/", pos: "n.", m: "入口；接触的机会", ex: "Students have access to the library 24 hours a day.", et: "学生可以全天候使用图书馆。" },
  { w: "accident", p: "/ˈæksɪdənt/", pos: "n.", m: "事故；意外", ex: "The accident happened on a rainy night.", et: "事故发生在一个雨夜。" },
  { w: "account", p: "/əˈkaʊnt/", pos: "n.", m: "账户；描述", ex: "He gave a detailed account of what happened.", et: "他详细描述了发生的事情。" },
  { w: "accurate", p: "/ˈækjərət/", pos: "adj.", m: "精确的；准确的", ex: "The clock keeps accurate time.", et: "这个钟走得很准。" },
  { w: "achieve", p: "/əˈtʃiːv/", pos: "v.", m: "实现；达到", ex: "She achieved her goal of becoming a doctor.", et: "她实现了当医生的目标。" },
  { w: "acquire", p: "/əˈkwaɪər/", pos: "v.", m: "获得；学到", ex: "He acquired a good knowledge of French.", et: "他很好地掌握了法语。" },
  { w: "actual", p: "/ˈæktʃuəl/", pos: "adj.", m: "实际的；真实的", ex: "The actual cost was higher than expected.", et: "实际成本比预期的要高。" },
  { w: "adapt", p: "/əˈdæpt/", pos: "v.", m: "适应；改编", ex: "Children adapt to new environments quickly.", et: "孩子们能很快适应新环境。" },
  { w: "address", p: "/əˈdres/", pos: "n./v.", m: "地址；演说；处理", ex: "We must address this issue immediately.", et: "我们必须立即处理这个问题。" },
  { w: "adequate", p: "/ˈædɪkwət/", pos: "adj.", m: "充足的；适当的", ex: "We have adequate food for the trip.", et: "我们有足够的食物旅行。" },
  { w: "adjust", p: "/əˈdʒʌst/", pos: "v.", m: "调整；调节", ex: "You need to adjust the volume of the speaker.", et: "你需要调节扬声器的音量。" },
  { w: "administration", p: "/ədˌmɪnɪˈstreɪʃn/", pos: "n.", m: "管理；行政", ex: "The new administration promised to reduce taxes.", et: "新政府承诺减税。" },
  { w: "admire", p: "/ədˈmaɪər/", pos: "v.", m: "钦佩；赞赏", ex: "I admire her courage and determination.", et: "我钦佩她的勇气和决心。" },
  { w: "admit", p: "/ədˈmɪt/", pos: "v.", m: "承认；准许进入", ex: "He admitted that he had made a mistake.", et: "他承认犯了错误。" },
  { w: "adopt", p: "/əˈdɑːpt/", pos: "v.", m: "采用；收养", ex: "The school adopted a new teaching method.", et: "学校采用了新的教学方法。" },
  { w: "advance", p: "/ədˈvæns/", pos: "n./v.", m: "前进；进步", ex: "Technology has advanced rapidly in recent years.", et: "近年来技术发展迅速。" },
  { w: "advantage", p: "/ədˈvæntɪdʒ/", pos: "n.", m: "优势；有利条件", ex: "Speaking English is a great advantage in job hunting.", et: "会说英语在求职中是很大的优势。" },
  { w: "adventure", p: "/ədˈventʃər/", pos: "n.", m: "冒险；奇遇", ex: "Their trip to Africa was a real adventure.", et: "他们的非洲之旅是一次真正的冒险。" },
  { w: "advertise", p: "/ˈædvərtaɪz/", pos: "v.", m: "做广告；宣传", ex: "They advertise their products on television.", et: "他们在电视上为产品做广告。" },
  { w: "advice", p: "/ədˈvaɪs/", pos: "n.", m: "忠告；建议", ex: "Can you give me some advice on studying English?", et: "你能给我一些学英语的建议吗？" },
  { w: "affect", p: "/əˈfekt/", pos: "v.", m: "影响；感动", ex: "The weather can affect your mood.", et: "天气会影响你的心情。" },
  { w: "afford", p: "/əˈfɔːrd/", pos: "v.", m: "买得起；负担得起", ex: "Not everyone can afford a house in this city.", et: "并非所有人都能在这座城市买得起房。" },
  { w: "agency", p: "/ˈeɪdʒənsi/", pos: "n.", m: "代理处；机构", ex: "She works at a travel agency.", et: "她在一家旅行社工作。" },
  { w: "agenda", p: "/əˈdʒendə/", pos: "n.", m: "议程；日常工作事项", ex: "What's on the agenda for today's meeting?", et: "今天会议的议程是什么？" },
  { w: "agent", p: "/ˈeɪdʒənt/", pos: "n.", m: "代理人；特工", ex: "Our agent will contact you soon.", et: "我们的代理人会尽快联系您。" },
  { w: "agriculture", p: "/ˈæɡrɪkʌltʃər/", pos: "n.", m: "农业；农学", ex: "Agriculture is the backbone of the economy.", et: "农业是经济的支柱。" },
  { w: "airline", p: "/ˈerlaɪn/", pos: "n.", m: "航空公司", ex: "Which airline are you flying with?", et: "你坐哪家航空公司的航班？" },
  { w: "ancient", p: "/ˈeɪnʃənt/", pos: "adj.", m: "古代的；古老的", ex: "They visited an ancient temple in Kyoto.", et: "他们参观了京都的一座古寺。" },
  { w: "announce", p: "/əˈnaʊns/", pos: "v.", m: "宣布；通告", ex: "The company announced a new product launch.", et: "公司宣布推出新产品。" },
  { w: "annual", p: "/ˈænjuəl/", pos: "adj.", m: "每年的；年度的", ex: "The annual meeting will be held in Beijing.", et: "年会将在北京举行。" },
  { w: "apply", p: "/əˈplaɪ/", pos: "v.", m: "申请；应用", ex: "She decided to apply for the scholarship.", et: "她决定申请奖学金。" },
  { w: "approach", p: "/əˈproʊtʃ/", pos: "n./v.", m: "方法；接近", ex: "We need a new approach to this problem.", et: "我们需要用新方法来解决这个问题。" },
  { w: "appropriate", p: "/əˈproʊpriət/", pos: "adj.", m: "适当的；合适的", ex: "Wear appropriate clothes for the interview.", et: "面试时穿合适的衣服。" },
  { w: "approve", p: "/əˈpruːv/", pos: "v.", m: "赞成；批准", ex: "The committee approved the budget plan.", et: "委员会批准了预算计划。" },
  { w: "argue", p: "/ˈɑːrɡjuː/", pos: "v.", m: "争论；辩论", ex: "They argued about politics for hours.", et: "他们围绕政治争论了几个小时。" },
  { w: "arrange", p: "/əˈreɪndʒ/", pos: "v.", m: "安排；排列", ex: "I'll arrange a meeting for next Tuesday.", et: "我会安排下周二的会议。" },
  { w: "aspect", p: "/ˈæspekt/", pos: "n.", m: "方面；外观", ex: "We considered every aspect of the plan.", et: "我们考虑了计划的每个方面。" },
  { w: "assess", p: "/əˈses/", pos: "v.", m: "评估；评价", ex: "It's hard to assess the damage at this point.", et: "此刻很难评估损失。" },
  { w: "assign", p: "/əˈsaɪn/", pos: "v.", m: "分配；指派", ex: "The teacher assigned us a difficult project.", et: "老师给我们布置了一个困难的项目。" },
  { w: "assist", p: "/əˈsɪst/", pos: "v.", m: "帮助；援助", ex: "The nurse assisted the doctor during the surgery.", et: "护士在手术中协助医生。" },
  { w: "assume", p: "/əˈsuːm/", pos: "v.", m: "假设；承担", ex: "I assume you have read the report.", et: "我猜你已经读过报告了。" },
  { w: "attach", p: "/əˈtætʃ/", pos: "v.", m: "附加；系上", ex: "Please attach your resume to the email.", et: "请将简历附在邮件中。" },
  { w: "attain", p: "/əˈteɪn/", pos: "v.", m: "达到；获得", ex: "He attained the highest score in the class.", et: "他取得了全班最高分。" },
  { w: "attempt", p: "/əˈtempt/", pos: "n./v.", m: "尝试；企图", ex: "She made an attempt to climb the mountain.", et: "她尝试攀登那座山。" },
  { w: "attend", p: "/əˈtend/", pos: "v.", m: "出席；参加", ex: "Over 500 people attended the conference.", et: "超过500人参加了会议。" },
  { w: "attitude", p: "/ˈætɪtuːd/", pos: "n.", m: "态度；看法", ex: "Her positive attitude inspired everyone.", et: "她积极的态度激励了每个人。" },
  { w: "attract", p: "/əˈtrækt/", pos: "v.", m: "吸引；引起", ex: "The concert attracted a large audience.", et: "音乐会吸引了大量观众。" },
  { w: "audience", p: "/ˈɔːdiəns/", pos: "n.", m: "观众；听众", ex: "The audience applauded enthusiastically.", et: "观众热情地鼓掌。" },
  { w: "available", p: "/əˈveɪləbl/", pos: "adj.", m: "可用的；可获得的", ex: "Is this seat available?", et: "这个座位有人吗？" },
  { w: "average", p: "/ˈævərɪdʒ/", pos: "n./adj.", m: "平均的；普通的", ex: "The average temperature in July is 30°C.", et: "七月的平均气温是30度。" },
  { w: "avoid", p: "/əˈvɔɪd/", pos: "v.", m: "避免；躲开", ex: "Try to avoid eating too much sugar.", et: "尽量避免吃太多糖。" },
  { w: "balance", p: "/ˈbæləns/", pos: "n./v.", m: "平衡；余额", ex: "It's important to maintain a work-life balance.", et: "保持工作与生活的平衡很重要。" },
  { w: "behavior", p: "/bɪˈheɪvjər/", pos: "n.", m: "行为；举止", ex: "His behavior was very strange at the party.", et: "他在派对上的行为很奇怪。" },
  { w: "benefit", p: "/ˈbenɪfɪt/", pos: "n./v.", m: "利益；好处", ex: "Regular exercise benefits your health.", et: "经常锻炼有益健康。" },
  { w: "budget", p: "/ˈbʌdʒɪt/", pos: "n./v.", m: "预算", ex: "We need to stick to our budget this month.", et: "这个月我们需要坚持预算。" },
  { w: "burden", p: "/ˈbɜːrdn/", pos: "n.", m: "负担；重担", ex: "Don't burden yourself with too much work.", et: "不要给自己太多工作负担。" },
  { w: "calculate", p: "/ˈkælkjuleɪt/", pos: "v.", m: "计算；估计", ex: "Can you calculate the total cost?", et: "你能计算一下总成本吗？" },
  { w: "campaign", p: "/kæmˈpeɪn/", pos: "n.", m: "运动；战役", ex: "The company launched a marketing campaign.", et: "公司发起了一场营销活动。" },
  { w: "candidate", p: "/ˈkændɪdət/", pos: "n.", m: "候选人；应试者", ex: "She is the best candidate for the job.", et: "她是这个职位的最佳候选人。" },
  { w: "capable", p: "/ˈkeɪpəbl/", pos: "adj.", m: "有能力的；能干的", ex: "He is capable of doing the job well.", et: "他能把工作做好。" },
  { w: "capacity", p: "/kəˈpæsəti/", pos: "n.", m: "容量；能力", ex: "The stadium has a capacity of 50,000.", et: "体育场可容纳五万人。" },
  { w: "category", p: "/ˈkætəɡɔːri/", pos: "n.", m: "种类；类别", ex: "Books are divided into different categories.", et: "书籍被分成不同的类别。" },
  { w: "challenge", p: "/ˈtʃælɪndʒ/", pos: "n./v.", m: "挑战；质疑", ex: "Learning a new language is a challenge.", et: "学习一门新语言是一种挑战。" },
  { w: "character", p: "/ˈkærəktər/", pos: "n.", m: "性格；角色；字符", ex: "He has a strong but gentle character.", et: "他性格坚强但温和。" },
  { w: "chemical", p: "/ˈkemɪkl/", pos: "adj./n.", m: "化学的；化学品", ex: "Some chemicals are harmful to the environment.", et: "有些化学品对环境有害。" },
  { w: "circumstance", p: "/ˈsɜːrkəmstæns/", pos: "n.", m: "情况；环境", ex: "Under no circumstances should you give up.", et: "在任何情况下都不应放弃。" },
  { w: "communicate", p: "/kəˈmjuːnɪkeɪt/", pos: "v.", m: "交流；通讯", ex: "We communicate via email every day.", et: "我们每天通过邮件交流。" },
  { w: "community", p: "/kəˈmjuːnəti/", pos: "n.", m: "社区；团体", ex: "She is active in the local community.", et: "她在当地社区很活跃。" },
  { w: "compare", p: "/kəmˈper/", pos: "v.", m: "比较；对比", ex: "Compare the two options before making a decision.", et: "做决定前先比较两个选项。" },
  { w: "compete", p: "/kəmˈpiːt/", pos: "v.", m: "竞争；比赛", ex: "Students compete for scholarships every year.", et: "学生每年为奖学金竞争。" },
  { w: "complex", p: "/kəmˈpleks/", pos: "adj.", m: "复杂的；合成的", ex: "This is a complex problem that needs careful thought.", et: "这是一个需要仔细思考的复杂问题。" },
  { w: "concept", p: "/ˈkɑːnsept/", pos: "n.", m: "概念；观念", ex: "The concept of time is hard to define.", et: "时间的概念很难定义。" },
  { w: "concern", p: "/kənˈsɜːrn/", pos: "n./v.", m: "关心；担忧", ex: "There is growing concern about climate change.", et: "人们对气候变化的担忧日益增长。" },
  { w: "conclude", p: "/kənˈkluːd/", pos: "v.", m: "总结；推断", ex: "We can conclude that the plan is feasible.", et: "我们可以得出结论，计划是可行的。" },
  { w: "confidence", p: "/ˈkɑːnfɪdəns/", pos: "n.", m: "信心；信任", ex: "She speaks English with great confidence.", et: "她非常自信地说英语。" }
];

const CET6_WORDS = [
  { w: "accommodate", p: "/əˈkɑːmədeɪt/", pos: "v.", m: "容纳；适应", ex: "The hotel can accommodate up to 500 guests.", et: "这家酒店最多可容纳500位客人。" },
  { w: "accumulate", p: "/əˈkjuːmjəleɪt/", pos: "v.", m: "积累；堆积", ex: "Dust had accumulated in the corners of the room.", et: "灰尘积聚在房间的角落里。" },
  { w: "acquisition", p: "/ˌækwɪˈzɪʃn/", pos: "n.", m: "获得；收购", ex: "The acquisition of new skills is essential for career growth.", et: "获得新技能对职业发展至关重要。" },
  { w: "advocate", p: "/ˈædvəkeɪt/", pos: "v./n.", m: "提倡；拥护者", ex: "She advocates equal pay for women.", et: "她主张女性同工同酬。" },
  { w: "aggregate", p: "/ˈæɡrɪɡət/", pos: "n./adj.", m: "总计；合计的", ex: "The aggregate profit exceeded expectations.", et: "总利润超出预期。" },
  { w: "alleviate", p: "/əˈliːvieɪt/", pos: "v.", m: "减轻；缓和", ex: "This medicine can alleviate the pain.", et: "这种药可以缓解疼痛。" },
  { w: "ambiguous", p: "/æmˈbɪɡjuəs/", pos: "adj.", m: "模棱两可的", ex: "His answer was ambiguous and confusing.", et: "他的回答模棱两可，令人困惑。" },
  { w: "amend", p: "/əˈmend/", pos: "v.", m: "修改；修正", ex: "The constitution was amended last year.", et: "宪法去年被修订了。" },
  { w: "analogy", p: "/əˈnælədʒi/", pos: "n.", m: "类比；类推", ex: "He drew an analogy between the brain and a computer.", et: "他把大脑和电脑做了类比。" },
  { w: "analyze", p: "/ˈænəlaɪz/", pos: "v.", m: "分析；解析", ex: "Scientists analyzed the data carefully.", et: "科学家们仔细分析了数据。" },
  { w: "anonymous", p: "/əˈnɑːnɪməs/", pos: "adj.", m: "匿名的", ex: "The donation came from an anonymous source.", et: "捐款来自一个匿名来源。" },
  { w: "anticipate", p: "/ænˈtɪsɪpeɪt/", pos: "v.", m: "预期；预料", ex: "We anticipate a significant increase in sales.", et: "我们预计销售额会大幅增长。" },
  { w: "apparatus", p: "/ˌæpəˈrætəs/", pos: "n.", m: "器械；设备", ex: "The laboratory has modern apparatus.", et: "实验室有现代化的设备。" },
  { w: "arbitrary", p: "/ˈɑːrbɪtreri/", pos: "adj.", m: "任意的；武断的", ex: "The decision seemed completely arbitrary.", et: "这个决定看起来完全是武断的。" },
  { w: "ascribe", p: "/əˈskraɪb/", pos: "v.", m: "归因于", ex: "He ascribed his success to hard work.", et: "他把成功归因于努力工作。" },
  { w: "assemble", p: "/əˈsembl/", pos: "v.", m: "集合；组装", ex: "The workers assemble cars on the production line.", et: "工人们在生产线上组装汽车。" },
  { w: "assess", p: "/əˈses/", pos: "v.", m: "评估；估价", ex: "The committee will assess the impact of the policy.", et: "委员会将评估该政策的影响。" },
  { w: "assignment", p: "/əˈsaɪnmənt/", pos: "n.", m: "任务；作业", ex: "The assignment is due next Friday.", et: "作业下周五截止。" },
  { w: "assumption", p: "/əˈsʌmpʃn/", pos: "n.", m: "假设；假定", ex: "Your assumption is based on incomplete data.", et: "你的假设基于不完整的数据。" },
  { w: "assurance", p: "/əˈʃʊrəns/", pos: "n.", m: "保证；确信", ex: "He gave me his assurance that he would come.", et: "他向我保证他会来。" },
  { w: "attain", p: "/əˈteɪn/", pos: "v.", m: "达到；实现", ex: "She attained her goal of becoming a professor.", et: "她实现了当教授的目标。" },
  { w: "attribute", p: "/əˈtrɪbjuːt/", pos: "v./n.", m: "归因于；属性", ex: "She attributes her success to hard work and luck.", et: "她把成功归因于努力和运气。" },
  { w: "authentic", p: "/ɔːˈθentɪk/", pos: "adj.", m: "真正的；真实的", ex: "This is an authentic Italian restaurant.", et: "这是一家正宗的意大利餐厅。" },
  { w: "autonomy", p: "/ɔːˈtɑːnəmi/", pos: "n.", m: "自治；自主权", ex: "The region was granted greater autonomy.", et: "该地区被授予了更大的自治权。" },
  { w: "benchmark", p: "/ˈbentʃmɑːrk/", pos: "n.", m: "基准；标准", ex: "This product sets a new benchmark for quality.", et: "该产品为质量树立了新基准。" },
  { w: "benevolent", p: "/bəˈnevələnt/", pos: "adj.", m: "仁慈的；慈善的", ex: "He was a benevolent old man who helped everyone.", et: "他是一位帮助所有人的仁慈老人。" },
  { w: "breach", p: "/briːtʃ/", pos: "n./v.", m: "违反；缺口", ex: "Selling the data was a breach of trust.", et: "出售数据是违背信任的行为。" },
  { w: "bureaucracy", p: "/bjʊˈrɑːkrəsi/", pos: "n.", m: "官僚主义；官僚机构", ex: "The project was delayed by bureaucracy.", et: "项目因官僚主义而延误。" },
  { w: "catalyst", p: "/ˈkætəlɪst/", pos: "n.", m: "催化剂；促使变化的人/物", ex: "The new policy was a catalyst for change.", et: "新政策是变革的催化剂。" },
  { w: "cater", p: "/ˈkeɪtər/", pos: "v.", m: "迎合；提供饮食", ex: "The restaurant caters to vegetarians.", et: "这家餐厅迎合素食者的需求。" },
  { w: "coherent", p: "/koʊˈhɪrənt/", pos: "adj.", m: "连贯的；一致的", ex: "She gave a coherent explanation of the events.", et: "她对事件给出了连贯的解释。" },
  { w: "coincide", p: "/ˌkoʊɪnˈsaɪd/", pos: "v.", m: "同时发生；一致", ex: "His arrival coincided with the beginning of the meeting.", et: "他的到达与会议开始时间恰好一致。" },
  { w: "collaborate", p: "/kəˈlæbəreɪt/", pos: "v.", m: "合作；协作", ex: "The two companies collaborated on the project.", et: "两家公司在这个项目上合作。" },
  { w: "commemorate", p: "/kəˈmeməreɪt/", pos: "v.", m: "纪念；庆祝", ex: "A statue was built to commemorate the hero.", et: "建了一座雕像来纪念这位英雄。" },
  { w: "compatible", p: "/kəmˈpætəbl/", pos: "adj.", m: "兼容的；相容的", ex: "This software is compatible with all operating systems.", et: "这个软件与所有操作系统兼容。" },
  { w: "compensate", p: "/ˈkɑːmpenseɪt/", pos: "v.", m: "补偿；赔偿", ex: "The company compensated him for the injury.", et: "公司为他的受伤提供了赔偿。" },
  { w: "complement", p: "/ˈkɑːmplɪment/", pos: "n./v.", m: "补充；补足", ex: "Red wine complements cheese perfectly.", et: "红酒与奶酪完美搭配。" },
  { w: "comply", p: "/kəmˈplaɪ/", pos: "v.", m: "遵从；服从", ex: "All employees must comply with safety regulations.", et: "所有员工必须遵守安全规定。" },
  { w: "comprehensive", p: "/ˌkɑːmprɪˈhensɪv/", pos: "adj.", m: "全面的；综合的", ex: "We need a comprehensive review of the system.", et: "我们需要对系统进行全面审查。" },
  { w: "compulsory", p: "/kəmˈpʌlsəri/", pos: "adj.", m: "强制的；义务的", ex: "Education is compulsory for children aged 6 to 15.", et: "6至15岁儿童的教育是义务性的。" },
  { w: "conceive", p: "/kənˈsiːv/", pos: "v.", m: "构想；设想", ex: "He conceived a brilliant plan for the startup.", et: "他为创业公司构想了一个绝妙的计划。" },
  { w: "consensus", p: "/kənˈsensəs/", pos: "n.", m: "共识；一致", ex: "The committee reached a consensus on the issue.", et: "委员会在这个问题上达成了共识。" },
  { w: "constitute", p: "/ˈkɑːnstɪtuːt/", pos: "v.", m: "构成；组成", ex: "Women constitute half of the workforce.", et: "女性占劳动力的一半。" },
  { w: "contemplate", p: "/ˈkɑːntəmpleɪt/", pos: "v.", m: "沉思；考虑", ex: "She contemplated the offer for several days.", et: "她考虑了这个提议好几天。" },
  { w: "controversy", p: "/ˈkɑːntrəvɜːrsi/", pos: "n.", m: "争论；争议", ex: "The new law caused a lot of controversy.", et: "新法律引发了很多争议。" },
  { w: "coordinate", p: "/koʊˈɔːrdɪneɪt/", pos: "v.", m: "协调；配合", ex: "She coordinates the activities of all departments.", et: "她协调所有部门的活动。" },
  { w: "correspond", p: "/ˌkɔːrəˈspɑːnd/", pos: "v.", m: "符合；通信", ex: "His story doesn't correspond with the facts.", et: "他的叙述与事实不符。" },
  { w: "credentials", p: "/krɪˈdenʃlz/", pos: "n.", m: "资格证书；凭证", ex: "Please bring your credentials to the interview.", et: "请携带你的资格证书来面试。" },
  { w: "crucial", p: "/ˈkruːʃl/", pos: "adj.", m: "至关重要的", ex: "Sleep is crucial for good health.", et: "睡眠对健康至关重要。" },
  { w: "deduce", p: "/dɪˈduːs/", pos: "v.", m: "推论；推断", ex: "From the evidence, we can deduce that he is guilty.", et: "从证据中我们可以推断他有罪。" },
  { w: "deficit", p: "/ˈdefɪsɪt/", pos: "n.", m: "赤字；不足", ex: "The company operated at a deficit last year.", et: "公司去年亏损运营。" },
  { w: "deliberate", p: "/dɪˈlɪbərət/", pos: "adj.", m: "故意的；深思熟虑的", ex: "It was a deliberate attempt to mislead us.", et: "那是故意误导我们的企图。" },
  { w: "deteriorate", p: "/dɪˈtɪriəreɪt/", pos: "v.", m: "恶化；变坏", ex: "His health deteriorated rapidly.", et: "他的健康状况迅速恶化。" },
  { w: "deviate", p: "/ˈdiːvieɪt/", pos: "v.", m: "偏离；背离", ex: "Don't deviate from the original plan.", et: "不要偏离原计划。" },
  { w: "diminish", p: "/dɪˈmɪnɪʃ/", pos: "v.", m: "减少；缩小", ex: "His influence diminished over time.", et: "他的影响力随时间减弱。" },
  { w: "discriminate", p: "/dɪˈskrɪmɪneɪt/", pos: "v.", m: "歧视；区别", ex: "It is illegal to discriminate based on race.", et: "基于种族的歧视是违法的。" },
  { w: "disposition", p: "/ˌdɪspəˈzɪʃn/", pos: "n.", m: "性格；倾向", ex: "She has a cheerful and friendly disposition.", et: "她性格开朗友好。" },
  { w: "divert", p: "/daɪˈvɜːrt/", pos: "v.", m: "转移；使转向", ex: "Traffic was diverted due to the accident.", et: "由于事故，交通被改道。" },
  { w: "dominate", p: "/ˈdɑːmɪneɪt/", pos: "v.", m: "支配；控制", ex: "The company dominates the smartphone market.", et: "该公司主导着智能手机市场。" },
  { w: "eligible", p: "/ˈelɪdʒəbl/", pos: "adj.", m: "有资格的；合适的", ex: "Only members are eligible to vote.", et: "只有会员才有资格投票。" },
  { w: "eliminate", p: "/ɪˈlɪmɪneɪt/", pos: "v.", m: "消除；淘汰", ex: "We need to eliminate unnecessary costs.", et: "我们需要消除不必要的开支。" },
  { w: "endeavor", p: "/ɪnˈdevər/", pos: "n./v.", m: "努力；尽力", ex: "We endeavor to provide the best service.", et: "我们努力提供最好的服务。" },
  { w: "enhance", p: "/ɪnˈhæns/", pos: "v.", m: "提高；增强", ex: "Music can enhance your learning experience.", et: "音乐可以增强你的学习体验。" },
  { w: "essence", p: "/ˈesns/", pos: "n.", m: "本质；精髓", ex: "Time is of the essence in emergencies.", et: "在紧急情况下时间至关重要。" },
  { w: "evaluate", p: "/ɪˈvæljueɪt/", pos: "v.", m: "评价；评估", ex: "Teachers evaluate students' performance regularly.", et: "老师定期评估学生的表现。" },
  { w: "evolve", p: "/ɪˈvɑːlv/", pos: "v.", m: "进化；演变", ex: "Technology continues to evolve at a rapid pace.", et: "技术继续以快速的步伐演变。" },
  { w: "exploit", p: "/ɪkˈsplɔɪt/", pos: "v.", m: "利用；开发；剥削", ex: "We need to exploit renewable energy sources.", et: "我们需要开发利用可再生能源。" },
  { w: "facilitate", p: "/fəˈsɪlɪteɪt/", pos: "v.", m: "促进；使便利", ex: "The new software facilitates communication between teams.", et: "新软件促进了团队间的沟通。" },
  { w: "fluctuate", p: "/ˈflʌktʃueɪt/", pos: "v.", m: "波动；起伏", ex: "Oil prices fluctuate frequently.", et: "油价经常波动。" },
  { w: "fundamental", p: "/ˌfʌndəˈmentl/", pos: "adj.", m: "基本的；根本的", ex: "Freedom is a fundamental human right.", et: "自由是一项基本人权。" },
  { w: "generate", p: "/ˈdʒenəreɪt/", pos: "v.", m: "产生；发电", ex: "Solar panels generate electricity from sunlight.", et: "太阳能板利用阳光发电。" },
  { w: "hypothesis", p: "/haɪˈpɑːθəsɪs/", pos: "n.", m: "假设；假说", ex: "The experiment confirmed our hypothesis.", et: "实验证实了我们的假设。" },
  { w: "implement", p: "/ˈɪmplɪment/", pos: "v.", m: "实施；执行", ex: "The company will implement the new policy next month.", et: "公司下个月将实施新政策。" },
  { w: "implication", p: "/ˌɪmplɪˈkeɪʃn/", pos: "n.", m: "含义；暗示", ex: "What are the implications of this decision?", et: "这个决定有什么影响？" },
  { w: "inclined", p: "/ɪnˈklaɪnd/", pos: "adj.", m: "倾向的；愿意的", ex: "She was inclined to agree with him.", et: "她倾向于同意他的观点。" },
  { w: "inherent", p: "/ɪnˈhɪrənt/", pos: "adj.", m: "固有的；内在的", ex: "There are inherent risks in any investment.", et: "任何投资都有内在风险。" },
  { w: "innovate", p: "/ˈɪnəveɪt/", pos: "v.", m: "创新；改革", ex: "Companies must innovate to stay competitive.", et: "公司必须创新才能保持竞争力。" },
  { w: "integrate", p: "/ˈɪntɪɡreɪt/", pos: "v.", m: "整合；融入", ex: "We need to integrate technology into education.", et: "我们需要将技术融入教育。" },
  { w: "intervene", p: "/ˌɪntərˈviːn/", pos: "v.", m: "干预；介入", ex: "The government intervened to save the bank.", et: "政府介入以拯救银行。" },
  { w: "legitimate", p: "/lɪˈdʒɪtɪmət/", pos: "adj.", m: "合法的；正当的", ex: "He has a legitimate reason for being absent.", et: "他缺席有正当理由。" },
  { w: "manifest", p: "/ˈmænɪfest/", pos: "v./adj.", m: "显示；明显的", ex: "His stress manifested as headaches.", et: "他的压力表现为头痛。" },
  { w: "negotiate", p: "/nɪˈɡoʊʃieɪt/", pos: "v.", m: "谈判；协商", ex: "They negotiated a peace treaty.", et: "他们通过谈判达成了和平条约。" }
];

// 合并所有单词，添加级别标记
const ALL_WORDS = [
  ...CET4_WORDS.map(w => ({ ...w, level: "CET-4" })),
  ...CET6_WORDS.map(w => ({ ...w, level: "CET-6" }))
];

// 导出供app.js使用
if (typeof window !== "undefined") {
  window.WORD_DATA = { CET4_WORDS, CET6_WORDS, ALL_WORDS };
}
